name: build

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'
  create:
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      max-parallel: 5
      matrix:
        platform: [
          android-arm, android-arm64, android-x64, android-x86, darwin-x64,
          linux-arm, linux-armv7, linux-arm64, linux-x64, linux-x86,
          windows-x64, windows-x86,
          windows-x64-shared, windows-x64-static, windows-x64-static-posix,
          windows-x86-shared, windows-x86-static, windows-x86-static-posix ]
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Build ${{ matrix.platform }} docker image
        shell: bash
        run: |
          make ${{ matrix.platform }}

      - name: Publish ${{ matrix.platform }} docker image
        if: success() && github.event_name == 'create' && startsWith(github.ref, 'refs/tags/')
        shell: bash
        run: |
          docker login -u="${{ secrets.DOCKER_USERNAME }}" -p="${{ secrets.DOCKER_PASSWORD }}"
          make push-${{ matrix.platform }}